name: Bug Report
description: Report a bug or defect.
title: "[BUG] "
labels: ["bug"]
projects: ["Project-Overworld/1"]
body:
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Describe the bug and how to reproduce this issue.
    validations:
      required: true
  - type: textarea
    id: bug-details
    attributes:
      label: Bug Details
      description: Add any additional details that relate to the bug.
      placeholder: Screenshots, links, additional information, etc.
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      description: What version of minecraft are you using?
      placeholder: 1.20.1
    validations:
      required: true
  - type: checkboxes
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: (No need to check these boxes)
      options:
        - label: Fix is implemented and merged into the dev-* branch.
        - label: All code is tested in the dev-* branch.